.PHONY: clean All

All:
	@echo "----------Building project:[ luckyNumber - Debug ]----------"
	@cd "luckyNumber" && "$(MAKE)" -f  "luckyNumber.mk"
clean:
	@echo "----------Cleaning project:[ luckyNumber - Debug ]----------"
	@cd "luckyNumber" && "$(MAKE)" -f  "luckyNumber.mk" clean
