.PHONY: clean All

All:
	@echo "----------Building project:[ B_Lucky_Numbers_easy - Debug ]----------"
	@cd "B_Lucky_Numbers_easy" && "$(MAKE)" -f  "B_Lucky_Numbers_easy.mk"
clean:
	@echo "----------Cleaning project:[ B_Lucky_Numbers_easy - Debug ]----------"
	@cd "B_Lucky_Numbers_easy" && "$(MAKE)" -f  "B_Lucky_Numbers_easy.mk" clean
