.PHONY: clean All

All:
	@echo "----------Building project:[ B_Two_Arrays_And_Swaps - Debug ]----------"
	@cd "/home/abdallah/Documents/Week 1.2 PST/B_Two_Arrays_And_Swaps" && "$(MAKE)" -f  "B_Two_Arrays_And_Swaps.mk"
clean:
	@echo "----------Cleaning project:[ B_Two_Arrays_And_Swaps - Debug ]----------"
	@cd "/home/abdallah/Documents/Week 1.2 PST/B_Two_Arrays_And_Swaps" && "$(MAKE)" -f  "B_Two_Arrays_And_Swaps.mk" clean
