.PHONY: clean All

All:
	@echo "----------Building project:[ Array_change_I - Debug ]----------"
	@cd "Array_change_I" && "$(MAKE)" -f  "Array_change_I.mk"
clean:
	@echo "----------Cleaning project:[ Array_change_I - Debug ]----------"
	@cd "Array_change_I" && "$(MAKE)" -f  "Array_change_I.mk" clean
