.PHONY: clean All

All:
	@echo "----------Building project:[ A_Second_Order_Statistics - Debug ]----------"
	@cd "A_Second_Order_Statistics" && "$(MAKE)" -f  "A_Second_Order_Statistics.mk"
clean:
	@echo "----------Cleaning project:[ A_Second_Order_Statistics - Debug ]----------"
	@cd "A_Second_Order_Statistics" && "$(MAKE)" -f  "A_Second_Order_Statistics.mk" clean
