.PHONY: clean All

All:
	@echo "----------Building project:[ 1668_Maximum_Repeating_Substring - Debug ]----------"
	@cd "1668_Maximum_Repeating_Substring" && "$(MAKE)" -f  "1668_Maximum_Repeating_Substring.mk"
clean:
	@echo "----------Cleaning project:[ 1668_Maximum_Repeating_Substring - Debug ]----------"
	@cd "1668_Maximum_Repeating_Substring" && "$(MAKE)" -f  "1668_Maximum_Repeating_Substring.mk" clean
